---
- name: a play that runs entirely on the ansible host
  hosts: 127.0.0.1
  connection: local
  tasks:
  - debug:
      msg: "{{ testMsg }}"
      
  - name: create ec2 instance
    ec2:
      aws_access_key: "AKIAICSHO7FSISSSLNCQ"
      aws_secret_key: "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"
      image: ami-0540a629cd8af8ad4
      wait: yes
      instance_type: t2.large
      group_id: sg-0fbb21db4643dca3a
      region: us-east-2
      count_tag:
        Name: testserver123456
      exact_count: 1
      instance_tags:
        Name: testserver123456
    register: ec2
